name: flutter_love_scope
description: `flutter_love_scope` provide flutter widgets for supporting solution base on flutter_scope and love.
version: 0.1.0-beta.1
homepage: https://github.com/LoveCommunity/flutter_love_scope

environment:
  sdk: ">=2.18.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  love: ^0.2.0
  flutter_scope: ^0.1.0-beta.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  test: ^1.17.12